{
  root: true,
  parser: "@typescript-eslint/parser",
  plugins: [ "@typescript-eslint", "jest" ],
  extends: [
    "eslint:recommended",
    "plugin:@typescript-eslint/recommended",
    "plugin:jest/recommended",
    "plugin:import/recommended"
  ],
  rules: {
    semi: [ 'error', 'never' ],
    no-shadow: off,
    no-useless-constructor: off,
    import/prefer-default-export: off,
    import/extensions: [ 'error', 'never' ],
    max-len: [
      error,
      {
        code: 145,
        ignorePattern: '^import .*',
        ignoreStrings: true,
        ignoreComments: true,
      },
    ],
    no-empty-function: off,
    object-curly-newline: off,
    no-unused-vars: off,
    '@typescript-eslint/no-unused-vars': [ error ],
    lines-between-class-members: off,
    class-methods-use-this: off,
    max-classes-per-file: off,
    no-param-reassign: off,
    import/no-extraneous-dependencies: off,
    no-await-in-loop: off,
    no-return-await: off,
    arrow-body-style: off,
    operator-linebreak: [ error, after ],
    no-console: error,
    comma-dangle: off,
    import/order: off,
    camelcase: off,
    arrow-parens: off,
    no-confusing-arrow: off,
    no-plusplus: off,
    func-names: off,
    wrap-iife: off,
    newline-per-chained-call: off,
    prefer-arrow-callback: off,
    space-before-function-paren: off,
    prefer-regex-literals: off,
    indent: [ 2, 2, { 'ignoredNodes': [ 'PropertyDefinition' ] } ],
    function-paren-newline: off,
    default-param-last: off,
    no-use-before-define: off,
    import/no-relative-packages: off,
    import/no-unresolved: off,
    implicit-arrow-linebreak: off,
    react-hooks/exhaustive-deps: off,
    no-useless-escape: off,
    object-curly-spacing: [ 'error', 'always' ],
    block-spacing: error,
    quotes: [ 'error', 'single' ],
  },
  overrides:
    [
      {
        files: [ '*.test.ts' ],
        rules:
          {
            no-loop-func: off,
            guard-for-in: off,
            jest/expect-expect:
              [ 'error', { assertFunctionNames: [ 'expect', 'fc.assert' ] } ],
            jest/no-conditional-expect: off,
            jest/no-disabled-tests: off,
          },
      },
    ]
}
